### PR TITLE
changing image type from Image to CompressedImage

### PR DESCRIPTION
**Pull request by Atine**
As noted in the question/issue in RoboCupAtHome/RuleBook#430, changing message type of image from `std_msgs/Image` to `std_msg/CompressedImage` will help reducing significant transmission time. When `rostopic hz`ing in our settings, it was 1-2 Hz before and 27-28 Hz after changing.

Need to install OpenCV though,  but should come with ROS Kinetic Kame by default.

### CODE REVIEW

**Comment by LoyVanBeek** [comment]
Nice. But I don't want to break other people's code that may be publishing an uncompressed image on the current topic (the example sets it to ```/usb_cam/image _raw```)

compressed isn't raw, but adding some option to subscribe to a second, compressed topic would be OK.

**Comment by atine** [comment]
You're right, I added back the `Image` subscriber. Now, Vizbox will listen on both `image` topic (which requires `sensor_msgs/Image`) and `image/compressed` (which requires `sensor_msgs/CompressedImage`) topic.

**Comment by LoyVanBeek** [comment]
This looks good, I'll try it out somewhere over the weekend. 
Thnx!

**Comment by atine** [comment]
Ok thank you!

**Pull request merged**
